POST http://localhost:3000/api/v1/book
Content-Type: application/json

{
    "title": "El enigma de la habitación 622",
    "genre": "Ficción contemporánea",
    "description": "Vuelve el «principito de la literatura negra contemporánea, el niño mimado de la industria literaria» (GQ): el nuevo thriller de Joël Dicker es su novela más personal. ",
    "author": "Joël Dicker",
    "publisher": "Alfaguara",
    "pages": 624,
    "image_url": "https://images-na.ssl-images-amazon.com/images/I/41KiZbwOhhL._SX315_BO1,204,203,200_.jpg"
}

#####
DELETE http://localhost:3000/api/v1/book/1

####
PUT http://localhost:3000/api/v1/book/1
Content-Type: application/json

{
    "title": "El enigma de la habitación 622",
    "genre": "Ficción contemporánea",
    "description": "Vuelve el «principito de la literatura negra contemporánea, el niño mimado de la industria literaria» (GQ): el nuevo thriller de Joël Dicker es su novela más personal. ",
    "author": "Joël Dicker",
    "publisher": "Alfaguara",
    "pages": 624,
    "image_url": "https://images-na.ssl-images-amazon.com/images/I/41KiZbwOhhL._SX315_BO1,204,203,200_.jpg"
}

##########
POST http://localhost:3000/api/v1/loan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im90cm9AbWFpbC5jb20iLCJpYXQiOjE2MzkxMzUzNDgsImV4cCI6MTYzOTIyMTc0OH0.sEZidJI_MbQhBCM2LVyCOHA-lMIclcMyvNd8zyC2x08
Content-Type: application/json

{
    "bookId":3,
    "userId":2
}

##########
PATCH http://localhost:3000/api/v1/loan/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQG1haWwuY29tIiwiaWF0IjoxNjM5MTM1MjQzLCJleHAiOjE2MzkyMjE2NDN9.mPLpojpTfWkuOZ7b1N0hWEyGEfSk5pfd-3TGUkspwfs
Content-Type: application/json

{
    "bookId":1,
    "userId":1
}

###############
POST  http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
    "email":"admin@mail.com",
    "password":"1234",
    "photo":"http://photo.png",
    "role":"admin"
}
##########

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"otro@mail.com",
    "password":"1234"
}


#########

POST https://library-rgl.herokuapp.com/api/v1/book
Content-Type: application/json

{
  "title": "exhalation",
  "genre": "novela",
  "description": "novela de ciencia ficción ...",
  "author": "Chiang, Ted",
  "publisher": "Narrativa Sexto Piso",
  "pages": 348,
  "image_url": "https://imagessl3.casadellibro.com/a/l/t5/93/9788417517793.jpg"
}