POST http://localhost:3000/api/v1/book
Content-Type: application/json

{
    "title": "El enigma de la habitación 622",
    "genre": "Ficción contemporánea",
    "description": "Vuelve el «principito de la literatura negra contemporánea, el niño mimado de la industria literaria» (GQ): el nuevo thriller de Joël Dicker es su novela más personal. ",
    "author": "Joël Dicker",
    "publisher": "Alfaguara",
    "pages": 624,
    "image_url": "https://images-na.ssl-images-amazon.com/images/I/41KiZbwOhhL._SX315_BO1,204,203,200_.jpg"
}

#####
DELETE http://localhost:3000/api/v1/book/1

####
PUT http://localhost:3000/api/v1/book/1
Content-Type: application/json

{
    "title": "El enigma de la habitación 622",
    "genre": "Ficción contemporánea",
    "description": "Vuelve el «principito de la literatura negra contemporánea, el niño mimado de la industria literaria» (GQ): el nuevo thriller de Joël Dicker es su novela más personal. ",
    "author": "Joël Dicker",
    "publisher": "Alfaguara",
    "pages": 624,
    "image_url": "https://images-na.ssl-images-amazon.com/images/I/41KiZbwOhhL._SX315_BO1,204,203,200_.jpg"
}

##########
POST http://localhost:3000/api/v1/loan
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im51ZXZvQG1haWwuY29tIiwiaWF0IjoxNjM3MzI0NjYxLCJleHAiOjE2Mzc0MTEwNjF9.7FPfjLz56q_ehPV26w0rhMi0jz9kv_iEgxMN96KTlP0
Content-Type: application/json

{
    "bookId":1,
    "userId":1
}

##########
PATCH http://localhost:3000/api/v1/loan/1
Content-Type: application/json

{
    "bookId":1,
    "userId":1
}

###############
POST  http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
    "email":"nuevo@mail.com",
    "password":"1234",
    "photo":"http://photo.png"
}
##########

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email":"nuevo@mail.com",
    "password":"1234"
}
